import 'package:flutter/material.dart';

ThemeData applicationDarkTheme = ThemeData(colorScheme: darkColorScheme);
ThemeData applicationTheme = ThemeData(colorScheme: lightColorScheme);

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF430F0F),
  onPrimary: Color(0xFFEEDCFF),
  primaryContainer: Color(0xFF681818),
  onPrimaryContainer: Color(0xFFECDCFF),
  secondary: Color(0xFF796005),
  onSecondary: Color(0xFFD8B9FF),
  secondaryContainer: Color(0xFF3E1C6F),
  onSecondaryContainer: Color(0xFFD5BAFF),
  tertiary: Color(0xFFEFB0FF),
  onTertiary: Color(0xFF4D1660),
  tertiaryContainer: Color(0xff3CCD42),
  onTertiaryContainer: Color(0xFFFAD7FF),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFFF66161),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFFFFFFFF),
  onBackground: Color(0xFFFFFFFF),
  surface: Color(0xFF430F0F),
  onSurface: Color(0xFF000000),
  surfaceVariant: Color(0xFF2CC6BC),
  onSurfaceVariant: Color(0xFFCBC4CF),
  outline: Color(0xFF958E99),
  onInverseSurface: Color(0xFF1D1B1E),
  inverseSurface: Color(0xFFE6E1E6),
  inversePrimary: Color(0xFF6D4EA1),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFFD5BAFF),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF430F0F),
  onPrimary: Color(0xFFEEDCFF),
  primaryContainer: Color(0xFF681818),
  onPrimaryContainer: Color(0xFFECDCFF),
  secondary: Color(0xFF796005),
  onSecondary: Color(0xFFD8B9FF),
  secondaryContainer: Color(0xFF3E1C6F),
  onSecondaryContainer: Color(0xFFD5BAFF),
  tertiary: Color(0xFFEFB0FF),
  onTertiary: Color(0xFF4D1660),
  tertiaryContainer: Color(0xff3CCD42),
  onTertiaryContainer: Color(0xFFFAD7FF),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFFF66161),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF1E1E1E),
  onBackground: Color(0xFFFFFFFF),
  surface: Color(0xFFFFFFFF),
  onSurface: Color(0xFFFFFFFF),
  surfaceVariant: Color(0xFF2CC6BC),
  onSurfaceVariant: Color(0xFFCBC4CF),
  outline: Color(0xFF958E99),
  onInverseSurface: Color(0xFF1D1B1E),
  inverseSurface: Color(0xFFE6E1E6),
  inversePrimary: Color(0xFF6D4EA1),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFFD5BAFF),
);
