name: Build and deploy ASP.Net Core app to Azure Web App - JirayaAPI

on:
  push:
    branches:
      - backend
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - backend
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_NAME: jiraya_api
      WORKING_DIRECTORY: backend/jiraya_api

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0'
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish --configuration Release --output 'jiraya_api'
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'JirayaAPI'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CEF7FB13FC3240AFBF6FBF388D18AB7B }}
